# Generated by roxyglobals: do not edit by hand

utils::globalVariables(c(
  "week", # <detect_extinct>
  "weekly_cases", # <detect_extinct>
  "cumulative", # <detect_extinct>
  "sim", # <detect_extinct>
  ":=", # <outbreak_model>
  "week", # <outbreak_model>
  "onset", # <outbreak_model>
  ".N", # <outbreak_model>
  "cumulative", # <outbreak_model>
  ":=", # <outbreak_setup>
  "isolated_time", # <outbreak_setup>
  "onset", # <outbreak_setup>
  "isolated", # <outbreak_setup>
  ":=", # <outbreak_step>
  "new_cases", # <outbreak_step>
  "isolated", # <outbreak_step>
  "asym", # <outbreak_step>
  "exposure", # <outbreak_step>
  "infector_iso_time", # <outbreak_step>
  "incubfn_sample", # <outbreak_step>
  "isolated_time", # <outbreak_step>
  "missed", # <outbreak_step>
  "onset", # <outbreak_step>
  "scenario", # <parameter_sweep>
  ".N", # <parameter_sweep>
  ":=", # <parameter_sweep>
  "sims", # <parameter_sweep>
  ":=", # <scenario_sim>
  "sim", # <scenario_sim>
  NULL
))
