# Generated by roxyglobals: do not edit by hand

utils::globalVariables(c(
  "week", # <detect_extinct>
  "weekly_cases", # <detect_extinct>
  "cumulative", # <detect_extinct>
  "sim", # <detect_extinct>
  "exposure", # <outbreak_model>
  "caseid", # <outbreak_model>
  "infector", # <outbreak_model>
  "onset", # <outbreak_model>
  "i.onset", # <outbreak_model>
  "week", # <outbreak_model>
  "cumulative", # <outbreak_model>
  "asymptomatic", # <outbreak_setup>
  "isolated_time", # <outbreak_setup>
  "onset", # <outbreak_setup>
  "new_cases", # <outbreak_step>
  "sampled", # <outbreak_step>
  "caseid", # <outbreak_step>
  "isolated_time", # <outbreak_step>
  "asymptomatic", # <outbreak_step>
  "onset", # <outbreak_step>
  "exposure", # <outbreak_step>
  "infector_asymptomatic", # <outbreak_step>
  "missed", # <outbreak_step>
  "infector_isolation_time", # <outbreak_step>
  "sampled", # <sample_offspring>
  "event_probs", # <sample_offspring>
  NULL
))
