# Generated by roxyglobals: do not edit by hand

utils::globalVariables(c(
  "week", # <detect_extinct>
  "weekly_cases", # <detect_extinct>
  "cumulative", # <detect_extinct>
  "sim", # <detect_extinct>
  "week", # <outbreak_model>
  "onset", # <outbreak_model>
  "cumulative", # <outbreak_model>
  "asym", # <outbreak_setup>
  "isolated_time", # <outbreak_setup>
  "onset", # <outbreak_setup>
  "new_cases", # <outbreak_step>
  "isolated", # <outbreak_step>
  "asym", # <outbreak_step>
  "onset", # <outbreak_step>
  "caseid", # <outbreak_step>
  "isolated_time", # <outbreak_step>
  "exposure", # <outbreak_step>
  "infector_iso_time", # <outbreak_step>
  "infector_asym", # <outbreak_step>
  "missed", # <outbreak_step>
  "scenario", # <parameter_sweep>
  "sims", # <parameter_sweep>
  "data", # <parameter_sweep>
  NULL
))
