#' Move forward one generation in the branching process
#'
#' @param case_data a `data.table`: cases in outbreak so far; initially
#'   generated by [outbreak_setup()]
#' @param offspring a `list` with class `<ringbp_offspring_opts>`: the
#'   offspring distribution `function`s for the \pkg{ringbp} model, returned
#'   by [offspring_opts()]. Contains three elements: `community`, `isolated`,
#'   and `asymptomatic`
#' @param delays a `list` with class `<ringbp_delay_opts>`: the
#'   delay distribution `function`s for the \pkg{ringbp} model, returned
#'   by [delay_opts()]. Contains two elements: `incubation_period` and
#'   `onset_to_isolation`
#' @param event_probs a `list` with class `<ringbp_event_prob_opts>`: the
#'   event probabilities for the \pkg{ringbp} model, returned by
#'   [event_prob_opts()]. Contains three elements: `asymptomatic`,
#'   `presymptomatic_transmission` and `symptomatic_ascertained`
#' @param interventions a `list` with class `<ringbp_intervention_opts>`:
#'   the intervention settings for the \pkg{ringbp} model, returned by
#'   [intervention_opts()]. Contains one element: `quarantine`
#'
#' @importFrom data.table data.table rbindlist fcase fifelse
#' @importFrom stats runif
#' @importFrom stats rnbinom
#'
#' @return A `list` with three elements:
#'   1. `$cases`: a `data.table` with case data
#'   2. `$effective_r0`: a `numeric` with the effective reproduction number
#'   3. `$cases_in_gen`: a `numeric` with the number of new cases in that
#'   generation
#' @autoglobal
#' @export
#'
#' @examples
#' offspring <- offspring_opts(
#'   community = \(n) rnbinom(n = n, mu = 2.5, size = 0.16),
#'   isolated = \(n) rnbinom(n = n, mu = 0, size = 1),
#'   asymptomatic = \(n) rnbinom(n = n, mu = 1.25, size = 0.16)
#' )
#' delays <- delay_opts(
#'   incubation_period = \(n) rweibull(n = n, shape = 2.32, scale = 6.49),
#'   onset_to_isolation = \(n) rweibull(n = n, shape = 1.65, scale = 4.28)
#' )
#' event_probs <- event_prob_opts(
#'   asymptomatic = 0,
#'   presymptomatic_transmission = 0.15,
#'   symptomatic_ascertained = 0
#' )
#' interventions <- intervention_opts(quarantine = FALSE)
#'
#' # generate initial cases
#' case_data <- outbreak_setup(
#'   initial_cases = 5,
#'   delays = delays,
#'   event_probs = event_probs
#' )
#' case_data
#' # generate next generation of cases
#' out <- outbreak_step(
#'   case_data = case_data,
#'   offspring = offspring,
#'   delays = delays,
#'   event_probs = event_probs,
#'   interventions = interventions
#' )
#' case_data <- out[[1]]
#' case_data
outbreak_step <- function(case_data,
                          offspring,
                          delays,
                          event_probs,
                          interventions) {

  checkmate::assert_data_table(case_data)
  checkmate::assert_class(offspring, "ringbp_offspring_opts")
  checkmate::assert_class(delays, "ringbp_delay_opts")
  checkmate::assert_class(event_probs, "ringbp_event_prob_opts")
  checkmate::assert_class(interventions, "ringbp_intervention_opts")

  # For each case in case_data, draw new_cases from a negative binomial
  # distribution with an R0 and dispersion dependent on if isolated = TRUE
  case_data[, new_cases := fcase(
    isolated, offspring$isolated(.N),
    asymptomatic, offspring$asymptomatic(.N),
    default = offspring$community(.N)
  )]

  # Select cases that have generated any new cases
  new_case_data <- case_data[new_cases > 0]
  # The total new cases generated
  total_new_cases <- case_data[, sum(new_cases), ]

  # If no new cases drawn, outbreak is over so return case_data
  if (total_new_cases == 0) {
    # If everyone is isolated it means that either control has worked or
    # everyone has had a chance to infect but didn't
    case_data$isolated <- TRUE

    effective_r0 <- 0
    cases_in_gen <- 0
    out <- list(case_data, effective_r0, cases_in_gen)
    names(out) <- c("cases", "effective_r0", "cases_in_gen")

    return(out)
  }

  # Compile a data.table for all new cases, new_cases is the amount of people
  # that each infector has infected
  prob_samples <- new_case_data[, list(
    # time when new cases were exposed, a draw from generation time based on
    # infector's onset
    exposure = incubation_to_generation_time(
      incubation_period_samples = rep(onset, new_cases),
      exposure_time = rep(exposure, new_cases),
      alpha = event_probs$alpha,
      latent_period = delays$latent_period
    ),
    # records the infector of each new person
    infector = rep(caseid, new_cases),
    # records when infector was isolated
    infector_isolation_time = rep(isolated_time, new_cases),
    # records if infector asymptomatic
    infector_asymptomatic = rep(asymptomatic, new_cases),
    # cases whose parents are asymptomatic are automatically missed;
    # will draw this for infector_asymptomatic == FALSE
    missed = TRUE,
    isolated = FALSE,
    new_cases = NA
  )][,
    # draws a sample to see if this person is asymptomatic
    asymptomatic := runif(.N) < event_probs$asymptomatic
  ][
    # keep only news cases that are pre-isolation
    exposure < infector_isolation_time
  ][,
    # onset of new case is exposure + incubation period sample
    onset := exposure + delays$incubation_period(.N)
  ]

  # draw a sample for missing
  prob_samples[
    infector_asymptomatic == FALSE,
    missed := runif(.N) > event_probs$symptomatic_ascertained
  ]

  prob_samples[, isolated_time := {
    ref_time <- onset + delays$onset_to_isolation(.N)
    fcase(
      # If asymptomatic, never isolated: time is Inf
      asymptomatic == TRUE, Inf,
      # If not asymptomatic, but are missed, isolated at your symptom onset
      missed == TRUE, ref_time,
      # if quarantine is in effect, isolated at the earlier of infector's or
      # infectee's isolation time
      rep(interventions$quarantine, .N), pmin(ref_time, infector_isolation_time),
      # isolated at symptom onset time if after infector isolation time,
      # otherwise at the earlier of infector and infectee isolation times
      default = pmin(ref_time, pmax(onset, infector_isolation_time))
    )
  }]

  # Chop out unneeded sample columns
  prob_samples[, c("infector_isolation_time", "infector_asymptomatic") := NULL]
  # Set new case ids for new people
  prob_samples[, caseid := case_data[.N, caseid] + seq_len(.N)]

  ## Number of new cases
  cases_in_gen <- nrow(prob_samples)

  ## Estimate the effective r0
  effective_r0 <- cases_in_gen / case_data[isolated == FALSE, .N]

  # Everyone in case_data so far has had their chance to infect and are
  # therefore considered isolated
  case_data$isolated <- TRUE

  # bind original cases + new secondary cases
  case_data <- data.table::rbindlist(list(case_data, prob_samples),
                                     use.names = TRUE)

  # Return
  list(
    cases = case_data,
    effective_r0 = effective_r0,
    cases_in_gen = cases_in_gen
  )
}
