#' Move forward one generation in the branching process
#'
#' @author Joel Hellewell
#'
#' @param case_data a `data.table`: cases in outbreak so far; initially
#'   generated by [outbreak_setup()]
#' @param r0_community a positive `numeric` scalar: reproduction number for
#'   non-isolated cases (must be >0)
#' @param r0_isolated a positive `numeric` scalar: reproduction number for
#'   isolated cases (must be >0)
#' @param r0_asymptomatic a positive `numeric` scalar: reproduction number for
#'   sub-clinical non-isolated cases (must be >0)
#' @param disp_community a positive `numeric` scalar: dispersion parameter for
#'   non-isolated cases (must be >0)
#' @param disp_isolated a positive `numeric` scalar: dispersion parameter for
#'   isolated cases (must be >0)
#' @param disp_asymptomatic a positive `numeric` scalar: dispersion parameter
#'   for sub-clincial non-isolated cases (must be >0)
#' @param incubation_period a `function`: a random number generating
#'   `function` that samples from incubation period distribution, the
#'   `function` accepts a single `integer` argument specifying the number of
#'   times to sample the incubation period (i.e. length of the `function`
#'   output).
#' @inheritParams incubation_to_generation_time
#' @param onset_to_isolation a `function`: a random number generating
#'   `function` that accepts a single `integer` argument specifying the
#'   length of the `function` output.
#' @param prop_ascertain a `numeric` scalar probability (between 0 and 1
#'   inclusive): proportion of infectious contacts ascertained by contact
#'   tracing
#' @param prop_asymptomatic a `numeric` scalar probability (between 0 and 1
#'   inclusive): proportion of cases that are completely asymptomatic
#'   (subclinical)
#' @param quarantine a `logical` scalar: whether quarantine is in effect, if
#'   `TRUE` then traced contacts are isolated before symptom onset; defaults to
#'   `FALSE`
#'
#' @importFrom data.table data.table rbindlist fcase fifelse
#' @importFrom stats runif
#' @importFrom stats rnbinom
#'
#' @return A `list` with three elements:
#'   1. `$cases`: a `data.table` with case data
#'   2. `$effective_r0`: a `numeric` with the effective reproduction number
#'   3. `$cases_in_gen`: a `numeric` with the number of new cases in that
#'   generation
#' @autoglobal
#' @export
#'
#' @examples
#' parameters <- parameters(
#'   initial_cases = 5,
#'   r0_community = 2.5,
#'   r0_isolated = 0,
#'   r0_asymptomatic = 1.25,
#'   disp_community = 0.16,
#'   disp_isolated = 1,
#'   disp_asymptomatic = 0.16,
#'   incubation_period = \(x) rweibull(n = x, shape = 2.32, scale = 6.49),
#'   prop_presymptomatic = 0.15,
#'   onset_to_isolation = \(x) rweibull(n = x, shape = 1.65, scale = 4.28),
#'   prop_ascertain = 0,
#'   prop_asymptomatic = 0,
#'   quarantine = FALSE
#' )
#'
#' # generate initial cases
#' case_data <- outbreak_setup(parameters = parameters)
#' case_data
#' # generate next generation of cases
#' out <- outbreak_step(
#'   case_data = case_data,
#'   parameters = parameters
#' )
#' case_data <- out[[1]]
#' case_data
outbreak_step <- function(case_data, parameters) {

  checkmate::assert_data_table(case_data)
  checkmate::assert_class(parameters, "ringbp_parameters")

  # For each case in case_data, draw new_cases from a negative binomial
  # distribution with an R0 and dispersion dependent on if isolated = TRUE
  case_data[, new_cases := rnbinom(
    .N,
    size = fifelse(
      isolated,
      parameters$disp_isolated,
      fifelse(
        asymptomatic,
        parameters$disp_asymptomatic,
        parameters$disp_community
      )
    ),
    mu = fifelse(
      isolated,
      parameters$r0_isolated,
      fifelse(asymptomatic, parameters$r0_asymptomatic, parameters$r0_community)
    )
  )]

  # Select cases that have generated any new cases
  new_case_data <- case_data[new_cases > 0]
  # The total new cases generated
  total_new_cases <- case_data[, sum(new_cases), ]

  # If no new cases drawn, outbreak is over so return case_data
  if (total_new_cases == 0) {
    # If everyone is isolated it means that either control has worked or
    # everyone has had a chance to infect but didn't
    case_data$isolated <- TRUE

    effective_r0 <- 0
    cases_in_gen <- 0
    out <- list(case_data, effective_r0, cases_in_gen)
    names(out) <- c("cases", "effective_r0", "cases_in_gen")

    return(out)
  }

  # Compile a data.table for all new cases, new_cases is the amount of people
  # that each infector has infected
  prob_samples <- new_case_data[, list(
    # time when new cases were exposed, a draw from generation time based on
    # infector's onset
    exposure = incubation_to_generation_time(
      rep(onset, new_cases), parameters$alpha
    ),
    # records the infector of each new person
    infector = rep(caseid, new_cases),
    # records when infector was isolated
    infector_isolation_time = rep(isolated_time, new_cases),
    # records if infector asymptomatic
    infector_asymptomatic = rep(asymptomatic, new_cases),
    # cases whose parents are asymptomatic are automatically missed;
    # will draw this for infector_asymptomatic == FALSE
    missed = TRUE,
    isolated = FALSE,
    new_cases = NA
  )][,
    # draws a sample to see if this person is asymptomatic
    asymptomatic := runif(.N) < parameters$prop_asymptomatic
  ][
    # keep only news cases that are pre-isolation
    exposure < infector_isolation_time
  ][,
    # onset of new case is exposure + incubation period sample
    onset := exposure + parameters$incubation_period(.N)
  ]

  # draw a sample for missing
  prob_samples[
    infector_asymptomatic == FALSE,
    missed := runif(.N) > parameters$prop_ascertain
  ]

  prob_samples[, isolated_time := {
    ref_time <- onset + parameters$onset_to_isolation(.N)
    fcase(
      # If asymptomatic, never isolated: time is Inf
      asymptomatic == TRUE, Inf,
      # If not asymptomatic, but are missed, isolated at your symptom onset
      missed == TRUE, ref_time,
      # if quarantine is in effect, isolated at the earlier of infector's or
      # infectee's isolation time
      rep(parameters$quarantine, .N), pmin(ref_time, infector_isolation_time),
      # isolated at symptom onset time if after infector isolation time,
      # otherwise at the earlier of infector and infectee isolation times
      default = pmin(ref_time, pmax(onset, infector_isolation_time))
    )
  }]

  # Chop out unneeded sample columns
  prob_samples[, c("infector_isolation_time", "infector_asymptomatic") := NULL]
  # Set new case ids for new people
  prob_samples[, caseid := case_data[.N, caseid] + seq_len(.N)]

  ## Number of new cases
  cases_in_gen <- nrow(prob_samples)

  ## Estimate the effective r0
  effective_r0 <- cases_in_gen / case_data[isolated == FALSE, .N]

  # Everyone in case_data so far has had their chance to infect and are
  # therefore considered isolated
  case_data$isolated <- TRUE

  # bind original cases + new secondary cases
  case_data <- data.table::rbindlist(list(case_data, prob_samples),
                                     use.names = TRUE)

  # Return
  out <- list(case_data, effective_r0, cases_in_gen)
  names(out) <- c("cases", "effective_r0", "cases_in_gen")

  return(out)
}
