# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
#
# Reproduce locally by running:
# ```r
# pak::pak("any::covr", dependencies = "Config/Needs/coverage")
# covr::codecov(quiet = FALSE)
# ```
on:
  push:
    branches: [main, master]
    paths:
      - 'R/**'
      - 'src/**'
      - 'tests/**'
      - 'inst/**'
      - 'DESCRIPTION'
      - '.github/workflows/test-coverage.yaml'
      - '.github/workflows/upload-coverage.yaml'
  merge_group:
  pull_request:
    paths:
      - 'R/**'
      - 'src/**'
      - 'tests/**'
      - 'inst/**'
      - 'DESCRIPTION'
      - '.github/workflows/test-coverage.yaml'
      - '.github/workflows/upload-coverage.yaml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

name: test-coverage

jobs:
  test-coverage:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v5
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::covr
            any::xml2
          needs: coverage

      - name: Test coverage
        run: |
          cov <- covr::package_coverage(quiet = FALSE)
          covr::to_cobertura(cov, "coverage.xml")
        shell: Rscript {0}

      - name: Save PR info
        run: |
          echo "${{ github.event.number }}" > pr_number.txt
          echo "${{ github.event.pull_request.head.sha }}" > pr_sha.txt
        if: github.event_name == 'pull_request'

      - name: Upload coverage data
        uses: actions/upload-artifact@v4
        with:
          name: coverage-data
          path: |
            coverage.xml
            pr_number.txt
            pr_sha.txt
